- name: Clean Up Dissemination Environment
  hosts: all
  become: no
  vars:
    app_dir: "/home/Project/ansible/roles/setup_environment/files"
    config_dir: "{{ app_dir }}/configs"
    log_dir: "/home/Project/ansible/playbooks/../logs"
    processes_to_kill:
      - dissemination
      - freeRiderNode
      - overloadNode
      - silentNode
      - tshark

  tasks:
    - name: Kill dissemination and related processes if running
      shell: |
        set +e
        for proc in {{ processes_to_kill | join(" ") }}; do
          if pgrep -f "$proc" > /dev/null; then
            echo "Killing process $proc"
            pkill -9 -f "$proc"
          else
            echo "No $proc processes found."
          fi
        done
        exit 0
      args:
        executable: /bin/bash
      register: kill_processes_result
      ignore_errors: true
      failed_when: false

    - name: Free UDP ports used by dissemination
      shell: |
        set +e
        lsof -tiUDP | grep dissemination | xargs -r kill -9
        exit 0
      args:
        executable: /bin/bash
      register: port_cleanup_result
      ignore_errors: true
      failed_when: false

    - name: Remove logs, configurations, and binary
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ log_dir }}"
        - "{{ playbook_dir }}/logs"
        - "{{ config_dir }}"
        - "{{ app_dir }}/dissemination"
        - "{{ app_dir }}/freeRiderNode"
      ignore_errors: true

    - name: Ensure cleanup is logged
      shell: echo "Cleanup completed on {{ inventory_hostname }}" >> /tmp/cleanup.log
      args:
        executable: /bin/bash
