---
- name: Deploy Dissemination Application
  hosts: all
  become: no
  tasks:
    - name: Ensure application directory exists
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: directory

    - name: Copy application files to nodes
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../roles/setup_environment/files/"
        dest: "{{ app_path }}/"
        remote_src: no

    - name: Compile the dissemination application
      ansible.builtin.command:
        cmd: make
        chdir: "{{ app_path }}"
      args:
        creates: "{{ app_path }}/dissemination"

    - name: Ensure logs directory exists
      ansible.builtin.file:
        path: "{{ log_path | dirname }}"
        state: directory
